### ISSUE TITLE
Develop PEChefCard

### ISSUE THREAD

**Issue by Natanta94** [people-eat/web-app#117]
![Screenshot 2023-04-23 at 22 21 01](https://user-images.githubusercontent.com/127600750/233863917-d8ce982e-0720-4029-baff-dd3a18727a33.png)

**Comment by Natanta94** [comment]
The card should contain the following:
-Chef name
-Chef category
-Chef ranking (in brackets number of reviews)
- City
- Labels of categories of his menu
- Labels of cousines of his menu

**Comment by Natanta94** [comment]
On hover, the card to become a little bit bigger (pop out effect)

**Comment by Natanta94** [comment]
Change size of the card --> to be aligned with UX designer

**Comment by CemYil03** [comment]
- Rename `menus` to `menuKitchens`
- If `!menuKitchens.length` hide the row for the kitchens and add white space at bottom
- Investigate why `menus` in storybook is considered an object an dwhy category changes are not reflected

export interface PEChefCardProps {
    imageUrl?: string;
    name?: string;            <-- make non optional
    location?: string;        <-- make non optional
    rank?: string;              <-- make non optional
    rating: {
        average?: number;
        count?: number;
    };
    categories?: string[];   <-- make non optional
    menus?: string[];         <-- make non optional
}

**Comment by Natanta94** [comment]
- remove icon if no kitchen is available
