### ISSUE TITLE
Develop an booking request card ("open" status) for chefs

### ISSUE THREAD

**Issue by Natanta94** [people-eat/web-app#122]
![Screenshot 2023-04-23 at 22 46 05](https://user-images.githubusercontent.com/127600750/233865395-f5e5dc93-09de-438a-83f6-32c6f6cc7ce7.png)

**Comment by Natanta94** [comment]
On card should be the following:

order details (clickable)
Rezension ansehen (clickable)
date and time when the order was submitted
Title of the menu
Picture of chef, chefs name, event type (Anlass)
Total revenue of the order (Umsatz)
Event date, time
Number of people, address
Two buttons: "Ablehnen" and "Annehmen"

**Comment by CemYil03** [comment]
Change button labels to `decline` and `accept`
