### ISSUE TITLE
Develop a footer

### ISSUE THREAD

**Issue by Natanta94** [people-eat/web-app#128]
![Image](https://user-images.githubusercontent.com/127600750/236038303-f479e951-66ef-4b69-badb-763124bc5944.png)

**Comment by CemYil03** [comment]
- Instagram icon and PeopleEat logo missing
- Add Links
  - Hot to become a chef -> /how-to-chef
  - About us -> /about-us
  - Terms and Conditions -> /terms-and-conditions
  - Imprint -> /imprint
  - Data Privacy Policy -> /data-privacy-policy

**Comment by Natanta94** [comment]
add padding on left and right
