### ISSUE TITLE
PEDropDown - Single Select

### ISSUE THREAD

**Issue by Natanta94** [people-eat/web-app#189]
- change label from "Choice" to input parameter "label" (so that we can change it to "Kitchen" or "Category" ...)
- implement call back function, so that we get back which options were selected
- implement parameter for default state of dropdown (expanded/not expanded)

**Comment by CemYil03** [comment]
Not done yet.

**Comment by Natanta94** [comment]
Single select dropdown

**Comment by Natanta94** [comment]
Dropdown labels should show amount of selected items
