### ISSUE TITLE
Chef profile: Basic user info

### ISSUE THREAD

**Issue by Natanta94** [people-eat/web-app#212]
![Image](https://github.com/people-eat/web-app/assets/127600750/a669a1a4-30ca-41f3-adb6-5b005bdea9bc)

**Comment by Natanta94** [comment]
- First name
- Last name
- Birthday date
- Phone number

Each field should be editable

**Comment by CemYil03** [comment]
Chef if it works with urls for images

**Comment by Natanta94** [comment]
Picture should show up when we put a URL, not a static path. Add to storybook
