### ISSUE TITLE
Terms and Conditions - Link

### ISSUE THREAD

**Issue by CemYil03** [people-eat/web-app#374]

**Comment by CemYil03** [comment]
Looks crappy :)

![Image](https://github.com/people-eat/web-app/assets/42110001/abf7cfa7-a305-479e-b06e-4d49aaf21ab6)

**Comment by Natanta94** [comment]
- [ ] open link in new tab

**Comment by Daniel2810** [comment]
- [ ] add splitter translations
- [ ] link should be only one work "Terms & Conditions"
