### ISSUE TITLE
Public Menu - Page

### ISSUE THREAD

**Issue by CemYil03** [people-eat/web-app#415]
- [x] If user does not enter address - do not show "Reisekosten" position at all, make button disabled
- [x] Once user enters address - Reisekosten to be calculated and button to be enabled (if other obligatory fields are filled in)
- [x] "Not in radius" text to be displayed over location field if user does not fit to chef radius

**Comment by Natanta94** [comment]
- [ ] Menu public page step 1: include selection for adults and children and price calculation. Then a button "Weiter", which leads to next screen, where user provides other details to event.

![Image](https://github.com/people-eat/web-app/assets/127600750/4e5251a9-d7ce-4f7b-80e4-a53d55f8770c)

**Comment by Natanta94** [comment]
Menu booking request (step 2): user should provide other details to event on this page



![Image](https://github.com/people-eat/web-app/assets/127600750/d333a7d3-6470-4898-9be1-8da2b4c1014d)

**Comment by Natanta94** [comment]
- [ ] Button "Send request" is always visible
- [ ] Price summary is always visible (travel costs are calculated once address is there)
- [ ] If not address is there, travel costs show 0

**Comment by Natanta94** [comment]
- Payment steps (including fees):
    1. Calculate menu price
    2. Calculate travel costs
    3. Sum it up → Preliminary price
    4. 4% x Preliminary price = Customer Fee
    5. 18% x Menu price = Chef Fee
    6. Preliminary price + Customer Fee = Transaction to Stripe
    7. Stripe fee = 1.5% x Transaction to Stripe + 0.25€
    8. Final Amount to Transfer to Stripe = (Transaction to Stripe + 0.25€)/(1 - 1.5%)

**Comment by CemYil03** [comment]
menuPrice
travelPrice
customerFee = menuPrice * 0.04
cookFee = menuPrice * 1.18

stripeTransactionPrice = menuPrice + travelPrice + customerFee

finalPrice = (stripeTransactionPrice + 0.25 EUR) / (1-0.015)

stripeFee = finalPrice - stripeTransactionPrice

serviceFee = stripeFee + customerFee
